### ISSUE TITLE
DEPRECATION warning

### ISSUE THREAD

**Issue by mesbah** [Tonkpils/ember-sweetalert#11]
After upgrading ember from 2.12 to 2.18 I got this warning when I start ember

DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (...\node_modules\ember-sweetalert\node_modules\ember-cli-version-checker\src\npm-dependency-version-checker.js:11:33)

ember-cli: 2.18.0
node: 8.9.4
os: win32 x6

**Comment by lindyhopchris** [comment]
This is probably fixed on the `develop` branch but I need to double check.

**Comment by lindyhopchris** [comment]
Closing this as I believe it is fixed on `develop`.
