### ISSUE TITLE
Upgrade ember-cli-babel

### ISSUE THREAD

**Issue by mapeveri** [Tonkpils/ember-sweetalert#16]
I am having this warning, work with ember 3.5

![image](https://user-images.githubusercontent.com/6276555/47851216-b9746700-ddb6-11e8-8472-2eb5bff6c50c.png)

**Comment by lindyhopchris** [comment]
This is fixed on `develop`.

**Comment by mapeveri** [comment]
@lindyhopchris Hi, when will the new version be released in npm?

Thanks!

**Comment by lindyhopchris** [comment]
Hopefully the next couple of days.
