### ISSUE TITLE
Is this package stable?

### ISSUE THREAD

**Issue by joey8williams** [Tonkpils/ember-sweetalert#19]
Hey! I've used sweetalert2 a ton in vanilla js projects; I was wondering if this ember extension was stable or if it needed any help? I'm available to work if there are any known bugs/limitations etc. Thanks!

**Comment by lindyhopchris** [comment]
Hi! Yes this is definitely stable - I'm using it in production apps.

I tagged as `1.0.0-rc.1` to give people a chance to provide feedback - but I haven't had any, so this could probably now be released as `1.0.0`. I need to update the Ember version then do that. I'll try to get to that in the next week or so.

If you have any questions/suggestions when using the package, let me know!

**Comment by lindyhopchris** [comment]
Closing this as I've tagged `1.0` and also released a `2.0` that upgrades the package to use Glimmer components.

@joey8williams thanks for the offer of help. do feel free to open an issues/PRs for anything that you think needs adding or improving.
