### ISSUE TITLE
Broccoli error Ember 2.9.x

### ISSUE THREAD

**Issue by danilovaz** [Tonkpils/ember-sweetalert#3]
I'm trying to use your addon in `Ember 2.9.x` but when I run `ember server` I'm receiving this:
```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:   
```

Any Idea why this happening?

**Comment by lindyhopchris** [comment]
I got the same error - it was solved by running `bower install sweetalert2`

This package should run the bower install when you run `ember install ember-sweetalert` but it doesn't at the moment. Think adding the following:

``` js
return this.addBowerPackageToProject('sweetalert2', '^6.1.0');
```

to the `afterInstall` function in the project's blueprint should fix it.

**Comment by Tonkpils** [comment]
I've released a new version of the addon with the fix. Let me know if this fixes your issue @danilovaz

**Comment by danilovaz** [comment]
I'll do some tests about it. Thank's @Tonkpils

**Comment by herzzanu** [comment]
If it helps, I'm using `Ember 2.9.x`and it works.

**Comment by Tonkpils** [comment]
If you run into any issues, feel free to re-open this
