### ISSUE TITLE
Uncaught (in promise)

### ISSUE THREAD

**Issue by herzzanu** [Tonkpils/ember-sweetalert#5]
I'm getting the following errors when clicking the cancel button or the overlay

![image](https://cloud.githubusercontent.com/assets/2959519/20617565/66c96ba2-b2ea-11e6-84a9-97b7df5571d7.png)

**Comment by sametersan** [comment]
You can use like this;

.then((confirm)=> {
          console.log(confirm);
        },(dismiss)=>{
          console.log(dismiss);
        }

**Comment by victor95pc** [comment]
it's normal, take a look at sweet alert README file and you will see, I prefer writing like this when I don't care about the cancel button.
```javascript
promise.then((confirm)=> {
console.log(confirm);
}).catch(swal.noop);
```

**Comment by lindyhopchris** [comment]
Closing this as the latest development version of this package upgrades to SweetAlert 7, for which this isn't an issue.
