### ISSUE TITLE
Set defaults?

### ISSUE THREAD

**Issue by adambedford** [Tonkpils/ember-sweetalert#8]
Is it possible to set default configuration options somehow? For example, I always want `buttonsStyling: false` but I'd rather not have to set that for each alert

**Comment by Tonkpils** [comment]
I don't believe that's implemented but I'd be happy to take a PR!

**Comment by lindyhopchris** [comment]
This is implemented on the `develop` branch - I'm planning to do a `1.0.0-rc.1` tag soon.
