### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by Tonkpils** [Tonkpils/ember-sweetalert#9]
Unfortunately, I am not actively maintaining this and I have not dedicated too much time at keeping up with the Ember environment. I created this library as a way of learning Ember and had some hopes of doing some work in production with it. However, I was moved in a different direction and this project fell through the cracks.

There are a couple of issues that would be better tackled by someone that uses this actively and has more knowledge of Ember. The sweetalert2 project is fairly active and if there is a need for this project I would love to have it keep going. 

Ping me on this issue and I'd be happy to add you as a collaborator on the project.

**Comment by lindyhopchris** [comment]
@Tonkpils I'm using this library in multiple contexts and could help out.

I'd like to upgrade it to use Sweet Alert 7.0 that's just been released and get Sweet Alert imported via npm/yarn rather than bower.

**Comment by Tonkpils** [comment]
@lindyhopchris you now have contributor access 😄
